#!/bin/bash

# We assume the following are defined
#  AWS4C
#  PA2X
#  MARFS


# # For example:
#
# BASE=/root/jti/send.dir
# GIT=$BASE/git
#
# export AWS4C=$GIT/aws4c
# export PA2X=$GIT/PA2X
# export MARFS=$GIT/marfs


if [ -z "$AWS4C" ]; then
    echo "AWS4C undefined.  Set it to the location of your aws4c install"
    exit 1
elif [ -z "$PA2X" ]; then
    echo "PA2X undefined.  Set it to the location of your PA2X install"
    exit 1
elif [ -z "$MARFS" ]; then
    echo "MARFS undefined.  Set it to the location of your marfs install"
    exit 1
fi


# convenience
CONFIG=$MARFS/common/configuration/src
FUSE=$MARFS/fuse/src
UTILITIES=$MARFS/utilities/gpfs




function usage() {
    PROG=$1

    echo "build everything for marfs:  libaws4c, libconfig, libmarfs, marfs_fuse"
    echo ""
    echo "usage:  $PROG [ <code> [ <mdal> ] ]"
    echo "  <code> 0  = compile -O3, without logging"
    echo "  <code> 1  = compile -O3, with logging to syslog"
    echo "  <code> 2  = compile -g,  with logging to syslog"
    echo "  <code> 3  = compile -g,  without logging"
    echo
    echo "  <mdal> 0 = don't use MDAL"
    echo "  <mdal> 1 = use MDAL"
    echo
}


# --- build everything for marfs:  libaws4c, libconfig, libmarfs, marfs_fuse

CODE=$1
MDAL=$2


case $CODE in
    0)
        CONFIG_ARGS+=" DEBUG=0 CONFIG=$MARFSCONFIGRC"
        FUSE_ARGS+=" lean"
        ;;
    1)
        CONFIG_ARGS+=" CONFIG=$MARFSCONFIGRC"
        FUSE_ARGS+=" fast"
        ;;
    2)
        AWS4C_ARGS+=" DEBUG=1"
        CONFIG_ARGS+=" DEBUG=1 CONFIG=$MARFSCONFIGRC"
        FUSE_ARGS+=" DEBUG=0"
        UTILITY_ARGS+=" DEBUG=1"
        ;;
    3)
        CONFIG_ARGS+=" DEBUG=4 CONFIG=$MARFSCONFIGRC"
        AWS4C_ARGS+=" DEBUG=1"
        FUSE_ARGS+=" lean DEBUG=0"
        UTILITY_ARGS+=" DEBUG=1"
        ;;
    *)
        usage $0
        exit 1;
esac

if (( MDAL )); then
    FUSE_ARGS+=" USE_MDAL=1"
fi

CONFIG_ARGS+=" PARSE_DIR=$PA2X"
FUSE_ARGS+=" LIBAWS4C=$AWS4C"

echo "AWS4C_ARGS='$AWS4C_ARGS'"
echo "CONFIG_ARGS='$CONFIG_ARGS'"
echo "FUSE_ARGS='$FUSE_ARGS'"
echo




echo
echo "### ................................................................."
echo "### making libaws4c"
echo "### ( cd $AWS4C && make clean && make $AWS4C_ARGS )"
if ! ( cd $AWS4C && make clean && make $AWS4C_ARGS ); then
    echo "couldn't build $AWS4C"
    exit 1
fi

echo
echo "### ................................................................."
echo "### making required PA2X directory"
echo "### ( cd $PA2X && mkdir -p parse-inc )"
if ! ( cd $PA2X && mkdir -p parse-inc ); then
    echo "couldn't mkdir -p $PA2X/parse-inc"
    exit 1
fi

echo
echo "### ................................................................."
echo "### making libconfig"
echo "### ( cd $CONFIG && make clean && make $CONFIG_ARGS )"
if !( cd $CONFIG && make clean && make $CONFIG_ARGS ); then
    echo "couldn't build $CONFIG"
    exit 1
fi

echo
echo "### ................................................................."
echo "### making libmarfs"
echo "### ( cd $FUSE && make clean && make $FUSE_ARGS )"
if !( cd $FUSE && make clean && make $FUSE_ARGS ); then
    echo "couldn't build $FUSE"
    exit 1
fi
echo
echo "### ................................................................."
echo "### making utilities/common"
echo "### ( cd $UTILITIES/common/src && make clean && make $UTILITY_ARGS )"
if !( cd $UTILITIES/common/src && make clean && make $UTILITY_ARGS ); then
    echo "couldn't build $UTILITIES/common/src"
    exit 1
fi
echo
echo "### ................................................................."
echo "### making quotas"
echo "### ( cd $UTILITIES/quotas/src && make clean && make $UTILITY_ARGS )"
if !( cd $UTILITIES/quotas/src && make clean && make $UTILITY_ARGS ); then
    echo "couldn't build $UTILITIES/quotas/src"
    exit 1
fi
echo
echo "### ................................................................."
echo "### making garbage collection"
echo "### ( cd $UTILITIES/garbage-collection/src && make clean && make $UTILITY_ARGS )"
if !( cd $UTILITIES/garbage-collection/src && make clean && make $UTILITY_ARGS ); then
    echo "couldn't build $UTILITIES/garbage-collection/src"
    exit 1
fi
echo
echo "### ................................................................."
echo "### making packer"
echo "### ( cd $UTILITIES/packer/src && make clean && make $UTILITY_ARGS )"
if !( cd $UTILITIES/packer/src && make clean && make $UTILITY_ARGS ); then
    echo "couldn't build $UTILITIES/packer/src"
    exit 1
fi
echo
echo "### ................................................................."
echo "### making repacker"
echo "### ( cd $UTILITIES/repacker/src && make clean && make $UTILITY_ARGS )"
if !( cd $UTILITIES/repacker/src && make clean && make $UTILITY_ARGS ); then
    echo "couldn't build $UTILITIES/repacker/src"
    exit 1
fi
