#!/bin/bash
#
#
# This script reads the gpfs target directory (with packed objects) provided and
# uses file size and offset from xattr to read the object back into a file.
#
#

if [[ $# != 1 ]]; then
   echo "Usage:  $0 path_to_gpfs_md_files"
   echo
   exit 1
fi

# recovery info size hardcoded- this may change over time
recovery=2943

dir=`basename $1`
rm -rf ./testing/$dir
mkdir ./testing/$dir

#for i in `cat $1 | awk '{print $2}'`; do
# iterate through target directory
for i in `ls $1/*`; do
   # get object xattr
   echo $i
   objid=`getfattr -d $i | grep objid | cut -d '"' -f 2`
   echo $i $objid
   file=`basename $i`

   # get post xattr
   post=`getfattr -d $i | grep post | cut -d '"' -f 2` 

   # get offset and number of objects from post xattr
   offset=`echo $post | sed -e 's/\// /g' | sed -e 's/\./ /g' | awk '{print $5}'` 
   objects=`echo $post | sed -e 's/\// /g' | sed -e 's/\./ /g' | awk '{print $7}'`
   size=`ls -al $1/$file | awk '{print $5}'`
   echo SIZE:     $size
   echo OFFSET:   $offset
   echo OBJECTS:  $objects
   let end=$offset+$recovery+$size-1
   echo END_OBJECT:  $end

   echo $dir/$file
   # get the object and write to file
   curl -u `egrep '^root' ~/.awsAuth | cut -d ':' -f 2-3` --digest -v -H "Range: bytes=$offset-$end" http://10.135.0.30:81/$objid > ./testing/$dir/$file.packed   
done

