#!/bin/bash

#
#
# This script reads the gpfs target directory (with unpacked objects) provided and
# uses a curl command to read the object back into a file 
#
# The sequence for testing object packing:
#
# run make_uni scripts
# run get_unpacked_object
# run marfs_packer
# run get_packed_object > log 
# Check if log has ERROR otherwise unpacked object matched packed object
#


if [[ $# != 1 ]]; then
   echo "Usage $0 path_to_gpfs_md_files"
   echo
   exit 1
fi

dir=`basename $1`

mkdir ./testing/$dir

# iterate through target directory
for i in `ls $1/*`; do
   # get object xattr
   objid=`getfattr -d $i | grep objid | cut -d '"' -f 2`
   echo $i $objid
   file=`basename $i`
   dir=`basename $1`

   # get objct and write to file
   curl -u `egrep '^root' ~/.awsAuth | cut -d ':' -f 2-3` --digest -v -H 'Range: bytes=0-' http://10.135.0.30:81/$objid > ./testing/$dir/$file.unpacked   

done

