#!/bin/bash
# create a clone of the source file tree unsing truncated files in
# <dest>

function usage {
    echo 'Usage: ./make_file_trees <source-dir> <source> <dest>'
}

SOURCE_DIR=$1
SOURCE=$2
DEST=$3

SRC_TOP=`echo $SOURCE | cut -d / -f 1`
script=mktree_"$SRC_TOP"_$(date +%Y%m%d)

echo "mkdir $DEST/$SOURCE" >> $script

# walk the directory tree.
for file in `ls $SOURCE_DIR/$SOURCE`
do
    if [ -d $SOURCE_DIR/$SOURCE/$file ] ; then
        # recurse into the directory.
        ./$0 $SOURCE_DIR $SOURCE/$file $DEST
    else
        echo "truncate -s $(stat --printf=%s $SOURCE_DIR/$SOURCE/$file) $DEST/$SOURCE/$file" >> $script
    fi
done
    

