#!/bin/bash -e

# Fuse isn't intended to support parallel writes for a given writer, but
# many writers may write at the same time, and it shouldn't screw up.  This
# tests that.

function usage() {
    PNAME=$1
    echo "Usage:  $1 {big|small}"
}

if [[ $# != 1 ]]; then
    usage $0
    exit 1

elif [[ $1 == "small" ]]; then

    # --- small writes

    # deleting so truncates don't get involved
    for i in `seq 0 63`; do
        FILE=/marfs/jti/parallel.`printf "%02d" $i`
        rm -f $FILE &
    done

    for i in `seq 0 63`; do
        FILE=/marfs/jti/parallel.`printf "%02d" $i`
        echo test > $FILE &
    done
    wait

    echo  PASS

elif [[ $1 == "big" ]]; then

    # --- big writes

    for i in `seq 1 4`; do
        FILE=/marfs/jti/parallel.`printf "%02d" $i`
        dd if=/dev/zero of=$FILE bs=256M count=4 &
    done
    wait

    echo  PASS

else
    usage $0
    exit 1
fi


