#!/bin/bash

# Useful for separating the log output written from different threads
# in a common log, using the logging support in libmarfs, and libne.
# They both now have log-output that always has the thread-ID as the
# second token.

# ... unless they are writing to syslog, in which case the same program
# output ends up with the TID in column 5.  Make it a command-line arg, so
# this will work with both kinds of logs.

if [[ $# != 2 ]]; then
   echo "Usage:  $0 <log_file> <tid_column>"
   echo
   exit 1
fi

LOG_FNAME=$1
TID_COL=$2

rm -f foo.log*

# for THR in `cat $LOG_FNAME | awk '/[0-9][a-f]/{print $2}' | sort | uniq`; do grep $THR $LOG_FNAME > foo.log.$THR; done

for THR in `cat $LOG_FNAME | sed -E 's/([ ]+)/ /g' | cut -d ' ' -f $TID_COL | sort | uniq`; do grep $THR $LOG_FNAME > foo.log.$THR; done