#!/bin/bash


function usage() {
    echo "Usage: $0 <tcpdump_output>"
    echo
    echo "create the output file like this:"
    echo "  term1 $ tcpdump -i eth2 -w tcpdump_output  [hangs until completion]"
    echo "  term2 $ my_app ..."
    echo "  term1 $ ctl-C"
    echo
}


if [[ $# != 1 ]]; then
    usage
    exit 1
fi
FILE=$1
GNUPLOT=${FILE}.gnuplot
ABS=${FILE}.abs

tcpdump -nr $FILE -tt \
    | grep '10.135.0.21' \
    | awk '{ if(!init){init=$1}; printf("%6.4f %8d %20s\n", $1-init, $NF, $1) }' \
    | nl \
    > $ABS

echo "writing $GNUPLOT"
cat > $GNUPLOT <<EOF
  # plot [0:30] '$FILE.abs' using 2:3 with impulses
  plot '$FILE.abs' using 2:3 with impulses
  set terminal jpeg
  set output '$FILE.jpg'
  # plot [0:30] '$FILE.abs' using 2:3 with impulses
  plot '$FILE.abs' using 2:3 with impulses
EOF


echo "running $GNUPLOT to produce $JPG"
gnuplot -persist $GNUPLOT
