#!/bin/bash
#
#
# This script reads the gpfs target directory (with packed objects) provided and
# uses file size and offset from xattr to read the object back into a file.
# The object is then compared to the unpacked object
#
# The sequence for testing object packing:
#
# run make_uni scripts
# run get_unpacked_object
# run marfs_packer
# run get_packed_object > log 
# Check if log has ERROR otherwise unpacked object matched packed object
#

if [[ $# != 2 ]]; then
   echo "Usage:  $0 test_file_dir path_to_/tmp_packed_log"
   echo "test_file_dir = directory undeneath testing directory (created by get_partiallly_packed)"
   exit 1
fi

# recovery info size hardcoded- this may change over time
recovery=2943

dir=$1

# iterate through target directory
for i in `cat $2 | awk '{print $2}'`; do
   echo $i
   # get object xattr
   objid=`getfattr -d $i | grep objid | cut -d '"' -f 2`
   echo $i $objid
   file=$i

   # get post xattr
   post=`getfattr -d $i | grep post | cut -d '"' -f 2` 

   # get offset and number of objects from post xattr
   offset=`echo $post | sed -e 's/\// /g' | sed -e 's/\./ /g' | awk '{print $5}'` 
   objects=`echo $post | sed -e 's/\// /g' | sed -e 's/\./ /g' | awk '{print $7}'`
   size=`ls -al $file | awk '{print $5}'`
   echo SIZE:     $size
   echo OFFSET:   $offset
   echo OBJECTS:  $objects
   let end=$offset+$recovery+$size-1
   echo END_OBJECT:  $end

   filename=`echo $i | cut -d "/" -f 9 | cut -d "." -f 1-2`
   echo $filename

   # get the object and write to file
   curl -u `egrep '^root' ~/.awsAuth | cut -d ':' -f 2-3` --digest -v -H "Range: bytes=$offset-$end" http://10.135.0.30:81/$objid > ./testing/$dir/$filename.repacked   
   diff ./testing/$dir/$filename.packed ./testing/$dir/$filename.repacked
 
   # compare this object to unpacked objec
   if [ $? -ne 0 ] 
   then
     echo ERROR ./testing/$filename.packed and ./testing/$filename.reeacked differ
   else 
     echo testing/$filename.packed and testing/$filename.unpacked are the same
  fi
done

