[package]
name = "marchive-tman"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version="0.4", features=["clock","std"]}
regex = "1.11"
serde = { version="1.0", features=["derive"] }
tokio = { version="1.45", features=["macros","rt-multi-thread","signal"] }
toml = "0.8"
