#!/bin/bash

# Run 'cat' on one of the practice fuse daemons, like this:
#
#  make hello
#  ./RUN hello ./mount_point
#
# We set up a handler to unmount on exit (or ctl-C).


if [[ $# -ne 2 ]]; then
	echo "Usage: $0 <executable> <mount_point>"
	exit 1
fi

# e.g. /users/jti/projects/mar_fs/fuse/test/filesys/mnt
PROG=$1
MOUNT=$2


bye() {
    echo "$0: trapped EXIT:  unmounting '$MOUNT'"
    fusermount -u $MOUNT
    exit
}

# trap bye INT
trap bye EXIT


# e.g. "hello my_mount_point"
eval "$PROG $MOUNT"

cat $MOUNT/hello

